### ISSUE TITLE
I forked your node-fptsync, and start my own branch

### ISSUE THREAD

**Issue by Nerom** [evanplaice/node-ftpsync#12]
@evanplaice  This ftpsync is too long with no update  , and I forked your project , Start my own branch , If you don't want me to do so , Let me know !

**Comment by evanplaice** [comment]
If you have an improvement to make I'd *expect* that you fork and branch the repo. Just submit a pull request once the changes are ready so I can merge them upstream.

I'd be more-than-happy to add you as a contributor (and likely provide commit access) if you're genuinely interested on improving the project.

I don't have an 'official' contributions guide written yet so here's a few ad-hoc guidelines:

1. Practice good code etiquette

  Fight the temptation to make 'superficial' changes. By which I mean, rearranging functions or changing the coding style in a way that doesn't add value.

  Most/all of the functions are written in an object declarative form, I'm not planning to change the style from the current form without a good justification.

2. Avoid adding dependencies

  In an effort to keep the library as lightweight as possible I'd like to keep the dependencies to a minimum. Dependencies for developing the library should always be added under devDependencies.

3. Don't change the API between versions

  A lot of though went into creating a clear/concise API that's straightforward and easy to implement. Keep in mind that other projects may depend on and extend the functionality of this one. API changes will be planned in advance and scheduled to occur during major version increments (ie 1.x.x, 2.x.x) only.

  For example, the grunt-node-ftpsync project depends on this project to provide ftp synchronization through the grunt task runner. In the future I'd also like to add support for gulp (or any other automation services that prove useful).

  The current versioning structure follows the semver standard. If you're not familiar with it take a moment to read through [the documentation](http://semver.org/) to better familiarize yourself.

Otherwise, happy coding.

**Comment by Nerom** [comment]
OK , got it !
